Geotracking Website/flasksite/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

Geotracking Website/flasksite/main/routes.py
from flask import render_template, request, Blueprint, flash, redirect, url_for
from flasksite.models import Post, emailsos, db
from flask_login import login_required
from flasksite.main.forms import EmailForm
from flasksite.main.utils import send_SoS_message

main = Blueprint('main', __name__)




@main.route("/")
@main.route("/index")
@main.route("/home")
def index():
    return render_template('index2.html')


@main.route("/Share")
def share():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('share.html', posts=posts)


@main.route("/about")
def about():
    return render_template('about.html', title='About')

@main.route("/adminteam")
def adminTeam():
    return render_template('adminteam.html', title='Contact Admin Team')

@main.route("/runaway")
def runaway():
    return render_template('runaway.html', title='SOS! Runaway Bike!')

@main.route("/sosmessage")
def sosmessage():
    return render_template('sosmessage.html', title='SOS!')


@main.route("/testsos", methods=['GET', 'POST'])
@login_required
def testsos():
    form = EmailForm()
    if form.validate_on_submit():
        email = emailsos(email=form.email.data)
        db.session.add(email)
        db.session.commit()
        send_SoS_message(email)
        flash('An email has been sent with the preloaded SoS Message.', 'info')
        return redirect(url_for('main.sosmessage'))
    return render_template('testsos.html', form=form)

@main.route("/development")
def development():
    return render_template('Development.html')

Geotracking Website/flasksite/map/routes.py
from flask import render_template, request, Blueprint, flash, url_for, redirect
from flask_login import login_required
from flasksite.map.forms import inputGPS
from flasksite.models import soughtgps, gps, streetandCity, bikeGps
from flasksite import db
from flasksite.map.utils import findNearest
from geopy.geocoders import Nominatim
geolocator = Nominatim(user_agent="flasksite")



map = Blueprint('map', __name__)

@map.route('/displaymap')
@login_required
def displaymap():
    currentbikeLoc = gps.query.order_by(gps.timestamp.desc()).first() #Get last updated coordinates
    lon,lat, ts = currentbikeLoc.longitude, currentbikeLoc.latitude, currentbikeLoc.timestamp #Put them into variables
    newts = (ts[0:10] + " " + ts[11:19]) #String Manipulation
    return render_template('displaymap.html', title='Displayed Map', longitude=lon, latitude=lat, timestamp = newts) #put into our map


@map.route('/nearest_bike', methods=['GET', 'POST'])
@login_required
def nearest_bike():
    form = inputGPS()
    if form.validate_on_submit():
        address = streetandCity(street=form.street.data , city= form.city.data )
        db.session.add(address)
        db.session.commit()
        flash('Your Coords Has Been Uploaded - Thank You', 'info')
        return redirect(url_for('map.displaymapandclosets'))
    return render_template('nearest_bike.html', form=form)

@map.route('/displaymapandclosets')
@login_required
def displaymapandclosets():
    closestpoint, distlist = findNearest()
    lon = closestpoint.pop('lon')
    lat = closestpoint.pop('lat')
    location = geolocator.reverse([lat,lon])
    address = location.address
    distlist.sort()
    currentbikeLoc = gps.query.order_by(gps.timestamp.desc()).first() #Get last updated coordinates
    lon,lat, ts = currentbikeLoc.longitude, currentbikeLoc.latitude, currentbikeLoc.timestamp #Put them into variables
    newts = (ts[0:10] + " " + ts[11:19]) #String Manipulation
    staticloc2 = bikeGps.query.filter_by(bike_id=2).order_by(bikeGps.id.desc()).first()
    staticloc3 = bikeGps.query.filter_by(bike_id=3).order_by(bikeGps.id.desc()).first()
    staticloc4 = bikeGps.query.filter_by(bike_id=4).order_by(bikeGps.id.desc()).first()
    staticloc5 = bikeGps.query.filter_by(bike_id=5).order_by(bikeGps.id.desc()).first()
    return render_template('distanceshow.html', closestpoint=address, distlistzero = distlist[0], distlistone = distlist[1],
                           distlisttwo = distlist[2], distlistthree = distlist[3], distlistfour = distlist[4],
    longitude = lon, latitude = lat, timestamp = newts,
    statlat2 = staticloc2.Latitude, statlon2 = staticloc2.Longtitude, statlat3 = staticloc3.Latitude,
      statlon3 = staticloc3.Longtitude, statlat4 = staticloc4.Latitude, statlon4 = staticloc4.Longtitude,
            statlat5 = staticloc5.Latitude, statlon5 = staticloc5.Longtitude
    )

@map.route('/staticmap')
@login_required
def staticmap():
    currentbikeLoc = gps.query.order_by(gps.timestamp.desc()).first() #Get last updated coordinates
    lon,lat, ts = currentbikeLoc.longitude, currentbikeLoc.latitude, currentbikeLoc.timestamp #Put them into variables
    newts = (ts[0:10] + " " + ts[11:19]) #String Manipulation
    staticloc2 = bikeGps.query.filter_by(bike_id=2).order_by(bikeGps.id.desc()).first()
    staticloc3 = bikeGps.query.filter_by(bike_id=3).order_by(bikeGps.id.desc()).first()
    staticloc4 = bikeGps.query.filter_by(bike_id=4).order_by(bikeGps.id.desc()).first()
    staticloc5 = bikeGps.query.filter_by(bike_id=5).order_by(bikeGps.id.desc()).first()
    return render_template('staticlandmarks.html', title='Displayed Map', longitude=lon, latitude=lat, timestamp = newts,
                           statlat2 = staticloc2.Latitude, statlon2 = staticloc2.Longtitude, statlat3 = staticloc3.Latitude,
                           statlon3=staticloc3.Longtitude, statlat4=staticloc4.Latitude, statlon4=staticloc4.Longtitude,
                           statlat5=staticloc5.Latitude, statlon5=staticloc5.Longtitude) #put into our map

Geotracking Website/flasksite/posts/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from flasksite import db
from flasksite.models import Post
from flasksite.posts.forms import PostForm

posts = Blueprint('posts', __name__)


@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!', 'success')
        return redirect(url_for('main.share'))
    return render_template('create_post.html', title='New Post',
                           form=form, legend='New Post')


@posts.route("/post/<int:post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)


@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your post has been updated!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html', title='Update Post',
                           form=form, legend='Update Post')


@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('main.share'))

Geotracking Website/flasksite/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from flasksite import db, bcrypt
from flasksite.models import User, Post
from flasksite.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                   RequestResetForm, ResetPasswordForm)
from flasksite.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.share'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.share'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.index'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.index'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account',
                           image_file=image_file, form=form)


@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=5)
    return render_template('user_posts.html', posts=posts, user=user)


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

Geotracking Website/flasksite/templates/Development.html
{% extends "layout.html" %}
{% block content %}

<br>
<br>
<h1>Ever Wonder How The Development Of This Webside came along?</h1>
<h2> Wonder No More. Below is a 1:1 Accurate Image Displaying the Procress</h2>
<br>
<br>
<p>Also Revelant for the Class Diagram....</p>


<br>
<br>
<img src="https://i.kym-cdn.com/entries/icons/original/000/022/524/tumblr_o16n2kBlpX1ta3qyvo1_1280.jpg" alt="Italian Trulli">



{% endblock content %}

Geotracking Website/flasksite/templates/adminteam.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Devloper/Admin Team</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <style>
  .fakeimg {
    height: 350px;
    background: #aaa;
  }
  </style>
</head>
<body>

  <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">Flask Website</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('main.index') }}">Home</a>
              <a class="nav-item nav-link" href="{{ url_for('main.share') }}">Share</a>
              <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
              <div class="btn-group dropright">
  <button type="button" class="btn dropdown-toggle bg-steel nav-link"  data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Bike Functionalities
  </button>
  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
    <a class="dropdown-item" href="{{ url_for('map.displaymap') }}">Track Bikes</a>
    <a class="dropdown-item" href="{{ url_for('map.nearest_bike') }}">Find Nearest Bike</a>
    <a class="dropdown-item" href="{{ url_for('main.runaway') }}">SOS! Bike Runaway</a>
  </div>
</div>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if current_user.is_authenticated %}
                <a class="nav-item nav-link" href="{{ url_for('posts.new_post') }}">New Post</a>
                <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
                <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
              {% else %}
                <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>

<div class="jumbotron text-center" style="margin-bottom:0">
  <h1>Admin/Developer Team</h1>
  <p>For Business Inquiries Please Read The Following Page</p>
</div>

<div class="container" style="margin-top:30px">
  <div class="row">
    <div class="col-sm-4">
      <h2>About The Team</h2>
      <h5>Photo Of The Team:</h5>
      <div class="fakeimg">Fake Image</div>
      <p>From Left: Name 1 - Name 2 - Name 3 - Name 4. (Perhaps with titles?)</p>
      <h3>Linked In & Business Emails</h3>
      <p>Please Inquire About Business/Developing Solutions </p>
      <ul class="nav nav-pills flex-column">
        <li class="nav-item">
          <a class="nav-link active" href="#">Active</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#">Disabled</a>
        </li>
      </ul>
      <hr class="d-sm-none">
    </div>
    <div class="col-sm-8">
      <h2>Team Members - Name One</h2>
      <h5>Name One, November 27, 2019</h5>
      <div class="fakeimg">Fake Image</div>
      <p>Title Of Name One</p>
      <p>Focus Area - Experterise - All Positive Quirks and Perks And Traits</p>
      <br>
      <h2>Team Member - Name Two</h2>
      <h5>Name One, November 27, 2019</h5>
      <div class="fakeimg">Fake Image</div>
      <p>Title Of Name One</p>
      <p>Focus Area - Experterise - All Positive Quirks and Perks And Traits</p>
      <br>
            <h2>Team Members</h2>
      <h5>Name One, November 27, 2019</h5>
      <div class="fakeimg">Fake Image</div>
      <p>Title Of Name One</p>
      <p>Focus Area - Experterise - All Positive Quirks and Perks And Traits</p>
      <br>
            <h2>Team Members</h2>
      <h5>Name One, November 27, 2019</h5>
      <div class="fakeimg">Fake Image</div>
      <p>Title Of Name One</p>
      <p>Focus Area - Experterise - All Positive Quirks and Perks And Traits</p>
      <br>
    </div>
  </div>
</div>

<div class="jumbotron text-center" style="margin-bottom:0">
  <h1 class="text-center"> Group 6 - IoT Solutions </h1>
  <h3>Your IoT Dream - Made Real</h3>
</div>

</body>
</html>

Geotracking Website/flasksite/templates/displaymap.html
{% extends "layout.html" %}
{% block content %}
<style>
.button {
  background-color: #4CAF50;
  border: none;
  color: white;
  padding: 15px 32px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  margin: 4px 2px;
  cursor: pointer;
  width:100%;
}

.header {
  padding: 15px;
  text-align: center;
  background: #1abc9c;
  color: white;
  font-size: 30px;
  width: 100%px; height: 125px;
}
</style>

  <title>Google Maps Multiple Markers</title>
  <script src="http://maps.google.com/maps/api/js?key=GETYOUROWNKEY"
          type="text/javascript"></script>

<div class="header">
  <h1>Track A Bike</h1>
  <p>Anywhere - Anytime</p>
</div>
<br>

  <div id="map" style="width: 100%; height: 600px;"></div>

  <script type="text/javascript">



    var locations = [
      //['Trøjborg', 56.166349, 10.215486, 4],
      //['Sønderhøj 30',56.119618, 10.158992, 5],
      ['Seen at {{timestamp}}', {{latitude}}, {{longitude}}, 1]
    ];

//Setting up a Map
    var map = new google.maps.Map(document.getElementById('map'), {
      zoom: 12,
      center: new google.maps.LatLng(56.161149, 10.169486),
      mapTypeId: google.maps.MapTypeId.ROADMAP
    });

    var infowindow = new google.maps.InfoWindow();


//Going through all of the markers
    var marker, i;

    for (i = 0; i < locations.length; i++) {
      marker = new google.maps.Marker({
        position: new google.maps.LatLng(locations[i][1], locations[i][2]),
        map: map
      });
//Add Listerners to when a marker is clicked
      google.maps.event.addListener(marker, 'click', (function(marker, i) {
        return function() {
          infowindow.setContent(locations[i][0]);
          infowindow.open(map, marker);
        }
      })(marker, i));
    }



</script>

<a href="{{ url_for('map.displaymap') }}" class="button">Refresh Map</a>


{% endblock content %}

Geotracking Website/flasksite/templates/distanceshow.html
{% extends "layout.html" %}
{% block content %}
<style>
.button {
  background-color: #4CAF50;
  border: none;
  color: white;
  padding: 15px 32px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  margin: 4px 2px;
  cursor: pointer;
  width:100%;
}

.header {
  padding: 15px;
  text-align: center;
  background: #1abc9c;
  color: white;
  font-size: 30px;
  width: 100%px; height: 125px;
}
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}

mystyle {
text-align: center;
}
</style>


  <title>Google Maps Multiple Markers</title>
  <script src="http://maps.google.com/maps/api/js?key=AIzaSyDwjHjhwNFRhorsXmP-E8vQTm2aqn04Lp0&callback=initMap"
          type="text/javascript"></script>



  <div id="map" style="width: 100%; height: 600px;"></div>

  <script type="text/javascript">




var timerID = setInterval(function() {
// My code here
}, 3 * 1000);

    var locations = [
      ['Tivoli Friheden', {{statlat2}}, {{statlon2}}, 4],
      ['Totally Not Henriks House',{{statlat3}}, {{statlon3}}, 5],
      ['Bilka Tilst', {{statlat4}}, {{statlon4}}, 3],
      ['Somewhere In Risskov', {{statlat5}},{{statlon5}}, 2],
      ['Seen at {{timestamp}}', {{latitude}}, {{longitude}}, 1]
    ];

    var map = new google.maps.Map(document.getElementById('map'), {
      zoom: 12,
      center: new google.maps.LatLng(56.161149, 10.169486),
      mapTypeId: google.maps.MapTypeId.ROADMAP
    });

    var infowindow = new google.maps.InfoWindow();


    var marker, i;

    for (i = 0; i < locations.length; i++) {
      marker = new google.maps.Marker({
        position: new google.maps.LatLng(locations[i][1], locations[i][2]),
        map: map
      });

      google.maps.event.addListener(marker, 'click', (function(marker, i) {
        return function() {
          infowindow.setContent(locations[i][0]);
          infowindow.open(map, marker);
        }
      })(marker, i));
    }



</script>

<a href="{{ url_for('map.displaymap') }}" class="button">Refresh Map</a>


<h2>Closet Bike is  at {{closestpoint}} </h2>

<p style="text-align: center;"> Below You Can See Other Distances </p>

<table>
  <tr>
    <th style="text-align: center;">Distance From You</th>
  </tr>
  <tr>
    <td>{{ distlistzero }} Kilometers - This Is The Closest One!</td>
  </tr>
  <tr>
    <td>{{ distlistone }} Kilometers</td>
  </tr>
  <tr>
    <td>{{ distlisttwo }} Kilometers</td>
  </tr>
  <tr>
    <td>{{ distlistthree }} Kilometers</td>
  </tr>
  <tr>
    <td>{{ distlistfour }} Kilometers</td>
  </tr>
</table>

{% endblock content %}

Geotracking Website/flasksite/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
                <small class="text-muted ml-2">
                    <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
                </small>
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
        </small>
    </div>
{% endblock content %}

Geotracking Website/flasksite/templates/post.html
{% extends "layout.html" %}
{% block content %}
  <article class="media content-section">
    <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
        <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
        {% if post.author == current_user %}
          <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
            <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
          </div>
        {% endif %}
      </div>
      <h2 class="article-title">{{ post.title }}</h2>
      <p class="article-content">{{ post.content }}</p>
    </div>
  </article>
  <!-- Modal -->
  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}